---
- name: show version
  hosts: routers
  gather_facts: false
#  connection: local

  vars:
    cli:
      username: admin
      password: admin
      timeout: 100
  tasks:
    - name: show version
      ios_config:
        provider: "(( cli ))"
        lines:
          - ipv6 unicast-routing
      register: print_output
