---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: get time snd dste
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"    

- hosts: routers nxos
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_ssh_pass: admin

  tasks:
    - name: show version
      cisco.ios.ios_command:
        commands: show version
      register: version

    - name: save to file
      copy: 
        content: "{{version.stdout[0]}}"
        dest: "~/ansible/output/{{hostvars.localhost.DTG}}-{{inventory_hostname}}-show-ver.txt"

- hosts: routers nxos
  tasks:
    - name: show ip int brie
      cisco.ios.ios_command:
        commands: show ip int brie
      register: ip_interfaces

    - name: save ip
      copy: 
        content: "{{ip_interfaces.stdout[0]}}"
        dest: "~/ansible/output/{{hostvars.localhost.DTG}}-{{inventory_hostname}}-ip-interfaces.txt"

