- name: show version
  hosts: routers
  gather_facts: false
  ansible_connection: ansible.netcommon.network_cli

  vars:
    cli:
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_user: admin
      ansible_password: admin

      timeout: 100
  tasks:
    - name: show version
      ios_command:
        commands: show version
